# Generated by Django 5.0.7 on 2024-09-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('cast_and_crew', models.TextField()),
                ('synopsis', models.TextField()),
                ('trailer_url', models.URLField(max_length=500)),
                ('movie_file', models.FileField(upload_to='movies/')),
                ('poster_image', models.ImageField(upload_to='posters/')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
        ),
    ]
