# Generated by Django 5.0.7 on 2024-10-08 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_shortvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='next_billing',
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('qr', 'QR Code')], max_length=50)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subscription')),
            ],
        ),
    ]
