# Generated by Django 5.0.7 on 2024-10-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_subscription_next_billing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI')], default='card', max_length=50),
        ),
    ]
